### ISSUE TITLE
Nested repository

### ISSUE THREAD

**Issue by Chaotique** [nilmaso/learn_git_master#1]
Dear Nil,
it seems as if Data_to_analyze were a git repository itself, which means that you have a nested structure: git repo inside git repo. I cloned learn_git_master recursively, but still I cannot see anything inside Data_to_analyze. 
Is there anything you wanted me to see?
All the best,
Franziska

**Comment by nilmaso** [comment]
Hi Franziska!
Yes, I unintentionally made Data_to_analyze a repository. Inside this directory there is the data I am analyzing and the code to create plots. I did not have the time to solve this issue, but should I locally create a new Data_to_analyze directory inside learn_git_master and then "push" the whole directory into my repository?

Best regards,
Nil

**Comment by Chaotique** [comment]
Hey Nil,
I'm sorry you ran into this problem. 

First, make a backup of Data_to_analyze somewhere.

Then, I think it should be enough if you go inside Data_to_analyze with
`cd Data_to_analyze`
and then remove .git the git way:
`git rm -r .git`
Then, with `git add .`, `git commit -m "something"` and `git push` it should be resolved.
Please let me know if you encounter any error messages on this path.

Looking forward to your code!
All the best,
Franziska

**Comment by Chaotique** [comment]
Hey Nil, me again.
You could also start a fresh clean repository ONLY for the data project. Actually we used learn_git_a_bit to play around and learn, but to have everything neatly separated, the data project could already be a second repository.
Good luck & have fun with your project,
Franziska

**Comment by nilmaso** [comment]
Hi Franziska,
Thank you so much for helping! I will try to erase the .git from Data_to_analyze and try again. 
Moreover, I also have to upload my data directory into my group's repository, and I think I will work from there. 

Best regards,
Nil

**Comment by Chaotique** [comment]
Sounds good! 
Make sure to not upload huge data files into github. It makes github slow and potentially fills the computers of your group very quickly. Just pick what they really need. And the rest you can hide from git with the .gitignore file. To know how it works: https://git-scm.com/docs/gitignore
Kind regards,
Franziska

**Comment by nilmaso** [comment]
Hey Franziska,

I followed the steps you wrote before and now the Data_to_analyze directory is accessible!

Thank you so much,
Nil

**Comment by Chaotique** [comment]
Can see you code now 0:-) Tell me in case you want me to look into sth specific.
Best wishes!
